[buildPlans.iosevka-mg-sans]
family = "Iosevka MG Sans"
spacing = "quasi-proportional"
serifs = "sans"
no-cv-ss = false
export-glyph-names = false
no-ligation = true

# Glyph variants were chosen to roughly mimic Computer Modern Sans-serif
# I deviated a bit, though, mostly for readability.  Ex: lowercase 'l'
[buildPlans.iosevka-mg-sans.variants.design]
capital-a = "straight-serifless"
capital-b = "standard-serifless"
capital-c = "serifless"
capital-d = "standard-serifless"
capital-e = "serifless"
capital-f = "serifless"
capital-g = "toothless-corner-serifless-hooked"
capital-h = "serifless"
capital-i = "serifless"
capital-j = "serifless"
capital-k = "straight-serifless"
capital-l = "serifless"
capital-m = "flat-bottom"
capital-n = "standard"
capital-p = "closed"
capital-q = "crossing"
capital-r = "straight"
capital-s = "serifless"
capital-t = "serifless"
capital-u = "toothless-rounded"
capital-v = "straight"
capital-w = "straight-flat-top"
capital-x = "straight-serifless"
capital-y = "straight-serifless"
capital-z = "straight-serifless"
a = "double-storey-serifless"
b = "toothed"
c = "serifless"
d = "toothed-serifless"
e = "flat-crossbar"
f = "flat-hook-crossbar-at-x-height"
g = "double-storey"
h = "straight"
i = "serifless"
j = "serifless"
k = "straight-serifless"
l = "flat-tailed"
m = "normal"
n = "straight"
p = "eared"
q = "straight"
r = "serifless"
s = "serifless"
t = "standard-short-neck"
u = "toothed"
v = "straight"
w = "straight-flat-top"
x = "straight-serifless"
y = "straight-turn"
z = "straight-serifless"
long-s = "bent-hook-tailed"
eszet = "sulzbacher-tailed"
turn-v = "straight"
lower-alpha = "crossing"
lower-delta = "rounded"
capital-gamma = "serifless"
lower-iota = "flat-tailed"
lower-lambda = "straight-turn"
lower-mu = "tailless"
lower-xi = "rounded"
cyrl-capital-zhe = "symmetric-connected"
cyrl-zhe = "symmetric-connected"
cyrl-capital-ze = "serifless"
cyrl-ze = "serifless"
cyrl-capital-ka = "symmetric-connected-serifless"
cyrl-ka = "symmetric-connected-serifless"
cyrl-el = "straight"
cyrl-en = "serifless"
cyrl-ef = "serifless"
cyrl-che = "standard"
cyrl-capital-u = "straight-turn"
cyrl-capital-ya = "straight"
cyrl-ya = "straight"
cyrl-yeri = "corner"
cyrl-yery = "corner"
zero = "unslashed"
one = "base"
two = "straight-neck"
three = "two-arcs"
four = "closed"
five = "vertical-upper-left-bar"
six = "open-contour"
seven = "bend-serifless"
eight = "two-circles"
nine = "open-contour"
tilde = "low"
asterisk = "penta-low"
underscore = "high"
pilcrow = "low"
caret = "medium"
paren = "normal"
brace = "straight"
number-sign = "slanted"
ampersand = "closed"
at = "fourfold"
dollar = "through"
cent = "through"
percent = "rings-continuous-slash"
bar = "natural-slope"
ascii-single-quote = "straight"
ascii-grave = "straight"
question = "smooth"
punctuation-dot = "round"
diacritic-dot = "round"
partial-derivative = "curly-bar"

[buildPlans.iosevka-mg-sans.widths.condensed]
shape = 500
menu  = 3
css   = "condensed"

[buildPlans.iosevka-mg-sans.widths.normal]
shape = 600
menu  = 5
css   = "normal"

[buildPlans.iosevka-mg-sans.widths.expanded]
shape = 664
menu  = 7
css   = "expanded"
