[buildPlans.iosevka-mg-typewriter]
family = "Iosevka MG Typewriter"
spacing = "fontconfig-mono"
serifs = "slab"
no-cv-ss = false
export-glyph-names = false

# Glyph variants were chosen to roughly mimic Computer Modern Typewriter.
# I deviated a bit, though, mostly based on personal preference.  Ex: '&'
[buildPlans.iosevka-mg-typewriter.variants.design]
capital-a = "straight-base-serifed"
capital-b = "standard-bilateral-serifed"
capital-c = "unilateral-serifed"
capital-d = "standard-bilateral-serifed"
capital-e = "serifed"
capital-f = "serifed"
capital-g = "toothed-serifed-capped"
capital-h = "serifed"
capital-i = "serifed"
capital-j = "serifed-both-sides"
capital-k = "curly-serifed"
capital-l = "serifed"
capital-m = "hanging"
capital-n = "standard"
capital-p = "closed"
capital-q = "crossing"
capital-r = "curly"
capital-s = "bilateral-serifed"
capital-t = "serifed"
capital-u = "toothless-rounded"
capital-v = "straight"
capital-w = "straight"
capital-x = "straight-serifed"
capital-y = "straight-serifed"
capital-z = "straight-serifed"
a = "double-storey-tailed"
b = "toothed-motion-serifed"
c = "unilateral-inward-serifed"
d = "tailed-serifed"
e = "flat-crossbar"
f = "flat-hook-serifed-crossbar-at-x-height"
g = "double-storey"
h = "straight"
i = "serifed"
j = "serifed"
k = "curly-serifed"
l = "serifed"
m = "normal"
n = "straight"
p = "eared"
q = "straight"
r = "serifed"
s = "bilateral-serifed"
t = "standard-short-neck"
u = "tailed"
v = "straight"
w = "straight-flat-top"
x = "straight-serifed"
y = "straight-turn"
z = "straight-serifed"
long-s = "bent-hook-tailed"
eszet = "sulzbacher-tailed"
turn-v = "straight"
lower-alpha = "crossing"
lower-delta = "flat-top"
capital-gamma = "serifed"
lower-iota = "serifed-flat-tailed"
lower-lambda = "straight-turn"
lower-mu = "tailed"
lower-xi = "flat-top"
cyrl-capital-zhe = "symmetric-connected"
cyrl-zhe = "symmetric-connected"
cyrl-capital-ze = "unilateral-serifed"
cyrl-ze = "unilateral-serifed"
cyrl-capital-ka = "symmetric-connected-serifed"
cyrl-ka = "symmetric-connected-serifed"
cyrl-el = "tailed"
cyrl-en = "serifed"
cyrl-ef = "serifed"
cyrl-che = "tailed"
cyrl-capital-u = "straight-turn"
cyrl-capital-ya = "curly"
cyrl-ya = "curly"
cyrl-yeri = "corner"
cyrl-yery = "corner"
zero = "unslashed"
one = "base"
two = "straight-neck"
three = "two-arcs"
four = "closed"
five = "vertical-upper-left-bar"
six = "open-contour"
seven = "bend-serifed"
eight = "two-circles"
nine = "open-contour"
tilde = "low"
asterisk = "penta-low"
underscore = "high"
pilcrow = "low"
caret = "medium"
paren = "normal"
brace = "straight"
number-sign = "slanted"
ampersand = "upper-open"
at = "fourfold"
dollar = "through"
cent = "through"
percent = "rings-continuous-slash"
bar = "natural-slope"
ascii-single-quote = "straight"
ascii-grave = "straight"
question = "smooth"
punctuation-dot = "round"
diacritic-dot = "round"
partial-derivative = "curly-bar"

[buildPlans.iosevka-mg-typewriter.widths.condensed]
shape = 500
menu  = 3
css   = "condensed"

[buildPlans.iosevka-mg-typewriter.widths.normal]
shape = 600
menu  = 5
css   = "normal"

[buildPlans.iosevka-mg-typewriter.widths.expanded]
shape = 664
menu  = 7
css   = "expanded"
